version: '3.8'

services:
  keyquorum:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
    restart: unless-stopped